export default {
    // Dimens
    zero: 0,
    fullFlex: 1,
    full: '100%',
    half: '50%',
    halfNum: 0.5,
    fullNum: 1.0,
    
    horizontal: 'row',
    column: 'column',
    spaceBetween: 'space-between',

    // Position
    positionAbsolute: 'absolute',
    positionRelative: 'relative',
    positionStatic: 'static',

    // Overflow
    overFlowHidden: 'hidden',

    // Align
    alignAuto: 'auto',
    alignBaseline: 'baseline',
    alignCenter: 'center',
    alignFlexEnd: 'flex-end',
    alignFlexStart: 'flex-start',
    alignStretch: 'stretch',
    alignRight: 'right',

    // margin/padding
    marginPrimarySmallest: 1,
    marginPrimaryQuarter: 2,
    marginPrimaryThird: 3,
    marginPrimaryHalf: 4,
    marginPrimaryHalf1_25X: 5,
    marginPrimaryHalf1_5X: 6,
    marginPrimaryHalf1_75X: 7,
    marginPrimary: 8,
    marginPrimary1_25X: 10,
    marginPrimary1_5X: 12,
    marginPrimary1_75X: 14,
    marginPrimary2X: 16,
    marginPrimary2_25X: 18,
    marginPrimary2_5X: 20,
    marginPrimary3X: 24,
    marginPrimary4X: 26,
    marginPrimary4_25X: 27,
    marginPrimary4_5X: 28,
    marginPrimary4_75X: 30,
    marginPrimary5X: 32,
    marginPrimary5_5X: 36,
    marginPrimary6X: 40,
    marginPrimary7X: 48,
    marginPrimary8X: 56,
    marginPrimary9X: 73,
    marginPrimary10X: 80,
    marginPrimary11X: 84,

    // Radii
    btnCornerRadius: 16,
    btnSmallCornerRadius: 8,
    inputRadius: 26,
    radiusSmallest: 4,
    radiusSmallest1_5X: 5,
    radiusSmaller: 6,
    radiusSmall: 8,
    radiusSmall1_5X: 9,
    radiusNormal: 10,
    radiusDefault: 12,
    radiusMedium: 16,
    radiusMax: 1000,

    // Offset
    offsetZero: 0,
    offsetSmallest: 1,
    offsetSmaller: 5,

    // Misc
    borderWidth: 1,
    borderWidthThick: 2,
    dividerHeight: 1,

    // View Sizes
    progressSize: 48,
    btnHeight: 61,
    btnHeightSmall: 36,
    inputHeight: 52,
    backBtnSize: 44,
    textBtnIconSize: 20,
    btnIconSize: 24,
    welcomeIcSize: 134,
    tabBarHeight: 50,
    dotSize: 10,
    activeDotWidth: 40,
    avatarSize: 105,

    // Font Weight
    fontWeightLight300: 300,
    fontWeightRegular400: 400,
    fontWeightMedium500: 500,
    fontWeightSemiBold600: 600,
    fontWeightBold: 700,
    fontWeightExtraBold: 800,

    // Fonts
    fontSizeSmallest: 10,
    fontSizeSmall: 12,
    fontSizeSmaller: 13,
    fontSizeNormal: 14,
    fontSizeNormal1_5X: 15,
    fontSizeMedium: 16,
    fontSizeMedium1_5X: 17,
    fontSizeLarge: 18,
    fontSizeXLarge: 19,
    fontSizeX2Large: 20,
    fontSizeX3Large: 22,
    fontSizeX4Large: 24,
    fontSizeX5Large: 26,
    fontSizeX6Large: 28,
    fontSizeX7Large: 30,
    fontSizeX8Large: 32,
    fontSizeX9Large: 34,
    fontSizeX10Large: 36,
    fontSizeLargest: 52,

    // Font Line Height
    lineHeightSmall: 10,
    lineHeightSmall1_5X: 14,
    lineHeightNormal: 16,
    lineHeightNormal1_5X: 17,
    lineHeightNormal1_75X: 18,
    lineHeightMedium: 20,
    lineHeightMedium1_5X: 21,
    lineHeightLarge: 24,
    lineHeightLarge1_5X: 26,
    lineHeightXLarge: 30,
    lineHeightX_5Large: 31,
    lineHeightX2Large: 32,
    lineHeightX3Large: 33,
    lineHeightX4Large: 36,
    lineHeightX5Large: 48,
    lineHeightLargest: 61,
} as const;
